# -*- coding: utf-8 -*-
"""carlos_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZ8dnaPdQXzPHWnwLvH5SnGDEIgqgpUS
"""

for i in range(0,10):
  print(i)
  if i == 5:
    break
print('terminou a identacao')





numero = 10
valor = 7.5
a, b, c = 7, 4, 'casa'
x = y = z = 'mesmo valor'
print(numero, valor)

palavra = 'palavra'
print(palavra[3])

meu_string = 'amor'
print(meu_string[1])

str1 = 'ola '
str2 = 'pessoal'
print(str1 + str2)

nome = input('whats your name? ')

numero = int(input("digite o numero "))
print(numero + 1)

x = 4
x == 4

from datetime import date
current_year = date.today().year
nome = input('qual seu nome ')
print(nome)
idade = int(input('qual sua idade? '))
ano = str((current_year - idade) + 100)
print(nome + ', voce tera 100 anos em '  + ano)

numero1 = int(input('digite tres numeros: '))
print (numero1)
numero2 = int(input('digite tres numeros: '))
print (numero2)
numero3 = int(input('digite tres numeros: '))
print (numero3)

if (numero1 >= numero2) and (numero2 >= numero3):
  maior=1
else:

num = 3
if num > 0:
  print('numero positivo')
else:
  if num == 0:
    print('zero')
  else:
    print('numero negativo')

num = int(input('enter a number'))
#mod = num % 2
if (num % 2 == 0):
  print(f'{num} numero par')
else:
  print(f'{num}numero impar')

numbers = [2, 3, 6, 8 ]
sum = 0
for val in numbers:
  sum = sum+val
  print('soma', sum)

for numero in range(0, 41, 4):
  print(numero)

for numero in range(4, 0, -1):
  print(numero)

genre = ['pop', 'rock', 'jazz']
for i in range(3):
  print('i like', genre[i])

count = 0
for letter in 'hello world':
  if (letter == 'l'):
      count =+ 1

fat = 1
numero = int(input('digite um numero '))
for i in range(1,numero):
  i +=1  
  fat = fat*i
  print('o fatorial e: ',fat)

fat = 1
i = 1
numero = int(input('digite um numero '))
while i <= numero:
  fat = fat* i
  i = i + 1
print('o fatorial e: ', fat)

nomes = ['Pedro', 'João', 'Leticia']
for n in nomes:
     print(n)
else:
     print("Todos os nomes foram listados com sucesso")

minha_lista =[1, "hello", 3.4]
print(minha_lista)
[1, 'hello', 1.4]

def armstrong(i)
sum = 0
temp = num
while temp > 0:
  digit = temp % 10
for i in range(1, 1000):
  print(i)
i = len(str(i))

n = str(input('digite a palavra: '))
n = len(str(n))
print(n)

import random
tam_list1 = int(input('entre com o tamanho  da primeira lista: '))
tam_list2 = int(input('entre com o tamanho  da segunda lista: '))
list1 = []
list2 = []
new_list = []
num = []
for x in range(tam_list1):
  list1.append(random.randint(1, 10))
for x in range(tam_list2):
  list2.append(random.randint(1, 10))
for num in list1:
  if num in list2:
    new_list.append(num)
print('primeira lista: ', list1)
print('segunda lista: ', list2)
print('nova lista: ', new_list)